# Generated by Django 6.1.1 on 2026-09-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerecord",
            name="labor_fee",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Biaya jasa"
            ),
        ),
    ]
