# Generated by Django 6.1.1 on 2026-09-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_servicerecord_labor_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerecord",
            name="cost",
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="servicerecord",
            name="labor_fee",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="Biaya jasa"
            ),
        ),
        migrations.AlterField(
            model_name="servicerecorditem",
            name="price_at_time_of_use",
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
