# Generated by Django 6.1.1 on 2026-09-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sparepart",
            name="price",
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
