# Generated by Django 6.1.1 on 2026-09-13 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inactive_threshold_days", models.PositiveIntegerField(default=90)),
                (
                    "new_customer_followup_delay_days",
                    models.PositiveIntegerField(default=3),
                ),
                ("reactivation_cooldown_days", models.PositiveIntegerField(default=14)),
                ("vip_min_service_count", models.PositiveIntegerField(default=4)),
                (
                    "vip_min_total_spending",
                    models.DecimalField(
                        decimal_places=2, default=1500000, max_digits=12
                    ),
                ),
                ("low_stock_threshold_default", models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("NEW_CUSTOMER", "New Customer"),
                            ("REACTIVATION", "Reactivation"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("HIGH", "High"), ("NORMAL", "Normal")],
                        default="NORMAL",
                        max_length=10,
                    ),
                ),
                ("scheduled_at", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to="customers.vehicle",
                    ),
                ),
            ],
        ),
    ]
