# Generated by Django 6.1.1 on 2026-09-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationsetting",
            name="margin_percentage_default",
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
    ]
