# Generated by Django 6.1.1 on 2026-09-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0002_automationsetting_margin_percentage_default"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="automationsetting",
            name="margin_percentage_default",
        ),
    ]
