# Generated by Django 6.1.1 on 2026-09-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0003_remove_automationsetting_margin_percentage_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationsetting",
            name="vip_min_total_spending",
            field=models.DecimalField(decimal_places=0, default=1500000, max_digits=12),
        ),
    ]
